name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures tags are fetched

    - name: Setup Git Config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Calculate New Tag Version
      id: versioning
      run: |
        # Fetch all tags
        git fetch --tags
        
        # Get the latest tag
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        
        # If no tags found, start with v1.0.0
        if [ -z "$latest_tag" ]; then
          echo "No tags found. Using default tag v1.0.0"
          new_version="v1.0.0"
        else
          # Increment the patch version
          echo "Latest tag: $latest_tag"
          IFS='.' read -ra ADDR <<< "${latest_tag#v}"
          if [ ${#ADDR[@]} -ne 3 ]; then
            echo "Tag format incorrect. Using default tag v1.0.0"
            new_version="v1.0.0"
          else
            major=${ADDR[0]}
            minor=${ADDR[1]}
            patch=${ADDR[2]}
            patch=$((patch + 1))
            new_version="v${major}.${minor}.${patch}"
          fi
        fi
        echo "New version: $new_version"
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Create and Push Tag
      if: env.new_version
      run: |
        git tag ${{ env.new_version }}
        git push origin ${{ env.new_version }}
        echo "Tag ${{ env.new_version }} created and pushed successfully."
