name: Code Formatting Check

on:
  push:
    branches:
      - main   # This triggers the action when code is pushed or merged into the 'main' branch

jobs:
  format:
    runs-on: ubuntu-latest   # The action runs on the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Specify the Python version

      - name: Install isort and black
        run: |
          pip install isort black

      - name: Run isort
        run: |
          isort .

      - name: Run black
        run: |
          black .

      # # If you want to commit the changes automatically back to the repo:
      # - name: Commit and push changes
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add .
      #     git commit -m "Apply isort and black formatting"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically provided by GitHub Actions
